language: elixir
matrix:
  include:
    - otp_release: 18.0
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.5
before_install:
  - sudo add-apt-repository ppa:rwky/graphicsmagick
  - sudo apt-get update
  - sudo apt-get install graphicsmagick
